version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: school_portal_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - school_portal_network

  app:
    build: .
    container_name: school_portal_api
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: 3000
      NODE_ENV: development
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - school_portal_network

volumes:
  postgres_data:

networks:
  school_portal_network:
    driver: bridge
